# Generated by Django 4.2.6 on 2023-11-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="US"
                    ),
                ),
                ("opening_hours", models.TimeField()),
                ("closing_hours", models.TimeField()),
            ],
            options={
                "verbose_name_plural": "stores",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "store",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="catalogue.store",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Short description or translation if dish name is not in English.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        default="images/default.png", null=True, upload_to="images/"
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menuitem",
                        to="catalogue.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        default=3,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menuitem",
                        to="catalogue.store",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.69, max_digits=6),
                ),
            ],
            options={
                "verbose_name_plural": "menuitems",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item", models.ManyToManyField(blank=True, to="catalogue.menuitem")),
                (
                    "category",
                    models.ManyToManyField(blank=True, to="catalogue.category"),
                ),
            ],
            options={
                "verbose_name_plural": "options",
            },
        ),
    ]
