# Generated by Django 4.2.6 on 2023-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
