# Generated by Django 4.2.6 on 2023-11-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_menuitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='store',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='catalogue.store'),
            preserve_default=False,
        ),
    ]
