# Generated by Django 4.2.6 on 2023-11-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_menuitem_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='short_description',
            new_name='alt_text',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='full_description',
            new_name='description',
        ),
    ]
