# Generated by Django 4.2.6 on 2023-11-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_remove_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.69, max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
