# Generated by Django 4.2.6 on 2023-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_remove_menuitem_size_menuitem_price_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ManyToManyField(to='catalogue.menuitem')),
            ],
            options={
                'verbose_name_plural': 'options',
            },
        ),
    ]
